# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  mysql:
    image: mysql:5.7-debian
    volumes:
      - theBridgeFormationMysql:/var/lib/mysql/
    environment:
      - MYSQL_DATABASE=9antraFormationBack
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
      - MYSQL_ROOT_PASSWORD=devpassword123
    ports:
      - 3306:3306

  backend:
    depends_on:
      - mysql
    image: 9antraformationback:latest
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/TheBridgeFormationDB?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - PHASE=prod
      - SPRING_DATASOURCE_PASSWORD=devpassword123
    ports:
      - 8080:8094

  # frontend:
  #   # depends_on:
  #   #   - backend
  #   image: thebridgeformation-frontend  
  #   build:
  #     context: ..
  #     dockerfile: deployment/Dockerfile
  #   environment:
  #     - HOST_NAMES=localhost
  #     - BACKEND_HOST=backend
  #     - BACKEND_PORT=8080
  #     - DOLLAR=$
  #   ports:
  #     - 80:80
volumes:
  theBridgeFormationMysql: